### ISSUE TITLE
Error When Running getCoveringCells

### ISSUE THREAD

**Issue by richardowright** [vekexasia/nodes2-ts#14]
### Overview
I'm trying to find a set of cells to cover a rectangular area, but I'm getting an error when trying to run it. 

### Code
```
const S2 = require('nodes2ts')
region_rect = new S2.S2LatLngRect(
    S2.S2LatLng.fromDegrees(-51.264871, -30.241701),
    S2.S2LatLng.fromDegrees(-51.04618, -30.000003))
coverer = new S2.S2RegionCoverer();
covering = coverer.getCoveringCells(region_rect)
```

### Error
```
TypeError: this.lat.isEmpty is not a function
    at S2LatLngRect.isEmpty (./node_modules/nodes2ts/dist/S2LatLngRect.js:109:25)
    at S2LatLngRect.getCapBound (./node_modules/nodes2ts/dist/S2LatLngRect.js:466:18)
    at S2RegionCoverer.getInitialCandidates (./node_modules/nodes2ts/dist/S2RegionCoverer.js:320:35)
    at S2RegionCoverer.getCoveringInternal (./node_modules/nodes2ts/dist/S2RegionCoverer.js:366:14)
    at S2RegionCoverer.getCoveringUnion (./node_modules/nodes2ts/dist/S2RegionCoverer.js:181:14)
    at S2RegionCoverer.getCoveringCells (./node_modules/nodes2ts/dist/S2RegionCoverer.js:156:24)
```

**Comment by richardowright** [comment]
Looks like I was using the wrong function to create the object. 

```
region_rect = new S2.S2LatLngRect.fromLatLng(
    S2.S2LatLng.fromDegrees(-51.264871, -30.241701),
    S2.S2LatLng.fromDegrees(-51.04618, -30.000003))
```
